version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: your_database
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgres_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
    volumes:
      - ./s3data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    # command: server /data
    command: server --address ":9000" --console-address ":9001" /data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"

volumes:
  pgdata:
    # external: true
  s3data:
    # external: true


