version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    env_file: .env
    networks:
      - mlops_network
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  

  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    env_file: .env
    networks:
      - mlops_network
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  minio-client:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb -p myminio/backup-bucket;
      exit 0;
      "
    networks:
      - mlops_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - mlops_network
    ports:
      - "5050:80"  # Порт, по которому будет доступен pgAdmin
    depends_on:
      - postgres

volumes:
  pgdata:
  minio-data:

networks:
  mlops_network:
    driver: bridge
